# Stage 1: Build Angular Application
FROM node:14 as builder

# ARG TARGETOS
# ARG TARGETARCH
# RUN echo "I'm building for $TARGETOS/$TARGETARCH"

# ENV BUILDX_ARCH="${TARGETOS:-linux}-${TARGETARCH:-arm64}"
# ENV BUILDX_VERSION="v0.11.2"

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
# RUN npm install node-sass --save-dev
RUN npm install sass
RUN npm install -g @angular/cli@11.2.8
RUN npm install

#Copy remaining code
COPY . .

#RUN build
ARG BUILD_ENV
RUN ng build --configuration=$BUILD_ENV --source-map=false

# Stage 2: Serve Angular Application
FROM nginx:alpine-slim

# Remove the default nginx configuration
RUN rm -rf /usr/share/nginx/html/*
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
# Copy the built Angular app from the previous stage
COPY --from=builder /app/dist/ /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
