export enum DASHBOARD_LN {
  TXT_ACCOUNTS = "TXT_ACCOUNTS",
  TXT_MANAGE_PROFILE = "TXT_MANAGE_PROFILE",  
  TXT_SIGN_OUT = "TXT_SIGN_OUT",
  TXT_HOME = "TXT_HOME",
  TXT_JOBS = "TXT_JOBS",
  TXT_CANDIDATES = "TXT_CANDIDATES",
  TXT_ANALYTICS = "TXT_ANALYTICS",
  TXT_SETTINGS = "TXT_SETTINGS",
  TXT_ADD_CLIENT = "TXT_ADD_CLIENT",

  //dashboard > stats
  TXT_UNDER_CONSTRUCTION = "TXT_UNDER_CONSTRUCTION",
  TXT_VISIT_SETTINGS = "TXT_VISIT_SETTINGS"
}