kind: Service
apiVersion: v1
metadata:
  name:  shop-app
  namespace: shop
spec:
  selector:
    app:  shop-app
  type:  ClusterIP
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  80
